version: '3.8'

services:
  django:
    build: .
    command: sh -c "sleep 5 && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "3030:8000"
    environment:
      - DJANGO_DB=django.db.backends.postgresql
      - DB_NAME=compose_postgres
      - DB_USER=postgres
      - DB_PASSWORD=1
      - DB_PORT=5432
      - DB_HOST=postgres_db
    depends_on:
      - postgres_db
    volumes:
      - static_volume:/home/app/code/static
      - media_volume:/home/app/code/media

  postgres_db:
    image: postgres:alpine3.17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=compose_postgres
      - POSTGRES_PASSWORD=1
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "1337:80"
    depends_on:
      - web
    volumes:
      - ./static:/home/app/code/static


volumes:
  pgdata: